uploads = []

[[generated]]
id = "2SG-r_Esv45p_ldkRkrRw"
uri = "file://client/public/apple-touch-icon.png"
type = "image"
title = "LAB fitness app icon"

[[generated]]
id = "v7JAs6VX6IE2JAPn5gx3-"
uri = "file://client/public/og-image.png"
type = "image"
title = "LAB og image"

[[outputs]]
id = "_tDyJMfp3ACaNsAMe0s21"
uri = "file://project.tar.gz"
type = "unspecified"
title = "Fitness Tracker — Full Project"

[[outputs]]
id = "BFIQ-sN3aaefbMmN9J0x1"
uri = "file://project.zip"
type = "unspecified"
title = "Fitness Tracker — Full Project (.zip)"
